const tickets={bento1:{number:"Coupon No.01",icon:"🍱",title:"お弁当リクエスト券",pass:"0414",message:"使用1週間ほど前に事前連絡願います。\n好きなおかず沢山入れるね🤍",photos:["images/bento1.jpg"]},bento2:{number:"Coupon No.02",icon:"🍱",title:"お弁当リクエスト券",pass:"0414",message:"使用1週間ほど前に事前連絡願います。\n張り切って作ります",photos:["images/bento2.jpg"]},movie:{number:"Coupon No.03",icon:"🎬",title:"好きな映画一緒に鑑賞券",pass:"1204",message:"なんだかんだ映画行ったことなかったから。\n多動症だけど悪しからず",photos:["images/movie.jpg"]},hug:{number:"Coupon No.04",icon:"🤍",title:"ぎゅー券",pass:"0705",message:"私からのハグです",photos:["images/hug.jpg"]},drive:{number:"Coupon No.05",icon:"🚗",title:"行きたい場所付き添い券",pass:"0429",message:"行きたいところについて行くよ、県外でも可",photos:["images/drive.jpg"]},stay:{number:"Coupon No.06",icon:"🌙",title:"お泊まり券",pass:"0725",message:"のんびりお酒飲みながらお泊まり会、\n枕投げでもしますか？☺️",photos:["images/stay.jpg"]},letter:{number:"Coupon No.07",icon:"💌",title:"手紙プレゼント券",pass:"0817",message:"いつもありがとう🥰\n心を込めて手紙を書きます✉️",photos:["images/letter.jpg"]},surprise:{number:"Coupon No.08",icon:"🎁",title:"サプライズ券",pass:"4869",message:"逆張りの私からのサプライズ、\nお楽しみにね🥰",photos:["images/surprise.jpg"]},secret:{number:"Coupon No.09",icon:"❓",title:"シークレット券",pass:"4869",message:"何が起こるか分かりません。",photos:["images/secret.jpg"]},final:{number:"FINAL COUPON",icon:"👑",title:"なんでも言うこと聞く券",pass:"8171204",message:"1日すぐるさんのものです",note:"有効期間：24時間\n8/17から利用可能",photos:["images/final.jpg"],final:true}};
const params=new URLSearchParams(window.location.search),ticketId=params.get("ticket")||"bento1",ticket=tickets[ticketId]||tickets.bento1;
const openButton=document.getElementById("openButton"),openGift=document.getElementById("openGift"),giftScreen=document.getElementById("giftScreen"),ticketScreen=document.getElementById("ticketScreen"),ticketPreview=document.getElementById("ticketPreview"),couponNumber=document.getElementById("couponNumber"),ticketIcon=document.getElementById("ticketIcon"),ticketTitle=document.getElementById("ticketTitle"),passInput=document.getElementById("passInput"),passButton=document.getElementById("passButton"),errorText=document.getElementById("errorText"),passArea=document.getElementById("passArea"),accepted=document.getElementById("accepted"),content=document.getElementById("content"),ticketMessage=document.getElementById("ticketMessage"),noteArea=document.getElementById("noteArea"),photoFrame=document.getElementById("photoFrame"),prevBtn=document.getElementById("prevBtn"),nextBtn=document.getElementById("nextBtn"),photoCount=document.getElementById("photoCount"),modal=document.getElementById("photoModal"),modalImage=document.getElementById("modalImage"),modalClose=document.getElementById("modalClose");
let currentPhoto=0;ticketPreview.textContent=ticket.icon;couponNumber.textContent=ticket.number;ticketIcon.textContent=ticket.icon;ticketTitle.textContent=ticket.title;ticketMessage.textContent=ticket.message;if(ticket.note)noteArea.textContent=ticket.note;if(ticket.final)document.body.classList.add("final-mode");
function openPresent(){openGift.classList.add("open");sparkle(22,true);setTimeout(()=>{giftScreen.classList.add("hidden");ticketScreen.classList.remove("hidden")},900)}
function checkPass(){if(passInput.value===ticket.pass){errorText.textContent="";passArea.classList.add("hidden");accepted.classList.remove("hidden");setTimeout(()=>{accepted.classList.add("hidden");content.classList.remove("hidden");renderPhoto();sparkle(ticket.final?42:26,ticket.final)},800)}else{errorText.textContent="パスコードが違います🥺";passInput.value=""}}
function renderPhoto(){const photos=ticket.photos||[],src=photos[currentPhoto];photoFrame.innerHTML="";if(!src){photoFrame.innerHTML="<p>📷 写真はあとからここに入れます</p>";photoCount.textContent="";prevBtn.style.visibility="hidden";nextBtn.style.visibility="hidden";return}const img=document.createElement("img");img.src=src;img.alt=ticket.title;img.onerror=()=>{photoFrame.innerHTML="<p>📷 写真はあとからここに入れます</p>";photoCount.textContent=""};img.onclick=()=>{modalImage.src=src;modal.classList.remove("hidden")};photoFrame.appendChild(img);if(photos.length>1){photoCount.textContent=`${currentPhoto+1} / ${photos.length}`;prevBtn.style.visibility="visible";nextBtn.style.visibility="visible"}else{photoCount.textContent="";prevBtn.style.visibility="hidden";nextBtn.style.visibility="hidden"}}
function changePhoto(direction){const photos=ticket.photos||[];if(photos.length<=1)return;currentPhoto=(currentPhoto+direction+photos.length)%photos.length;renderPhoto()}
function sparkle(count=22,gold=false){const symbols=gold?["✦","✨","✧"]:["✨","♡","✧"];for(let i=0;i<count;i++){const star=document.createElement("div");star.className="sparkle";star.textContent=symbols[Math.floor(Math.random()*symbols.length)];star.style.left=Math.random()*100+"vw";star.style.top=18+Math.random()*35+"vh";star.style.fontSize=14+Math.random()*18+"px";star.style.color=gold?"#d4af37":"#c7a66b";star.style.animationDelay=Math.random()*.18+"s";document.body.appendChild(star);setTimeout(()=>star.remove(),1500)}}
openButton.addEventListener("click",openPresent);openGift.addEventListener("click",openPresent);passButton.addEventListener("click",checkPass);prevBtn.addEventListener("click",()=>changePhoto(-1));nextBtn.addEventListener("click",()=>changePhoto(1));modal.addEventListener("click",()=>modal.classList.add("hidden"));modalClose.addEventListener("click",()=>modal.classList.add("hidden"));passInput.addEventListener("keydown",e=>{if(e.key==="Enter")checkPass()});
